version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build: .
    container_name: team_seeker_api
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "5000:5000"

volumes:
  mysql_data:
